spring:
  config:
    activate:
      on-profile: default
  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    show-sql: false
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

seckret_key: d4f'23p}793_+bg43'79'pd<./sabrg

---

spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      schema-locations: classpath:Dump20220524.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
server:
  port: 8080
---

spring:
  config:
    activate:
      on-profile: release
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    url: jdbc:mysql://fhdufhdu.iptime.org:3306/mim_local?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

---

spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: ~/test
  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/test  #접속 URL
    username: sa  # 사용자 이름 (로그인 시 사용)
    password:  # 사용자 암호 (로그인 시 사용)