spring:
  config:
    activate:
      on-profile: dev
  # sql:
  #   init:
  #     schema-locations: classpath:Dump20220511.sql
  #     mode: always
  jpa:
    generate-ddl: 'false'
    database: mysql
    defer-datasource-initialization: 'true'
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: 'true'
    show-sql: 'true'
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  datasource:
    password: dntjdtkak12!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://fhdufhdu.iptime.org:3306/mim?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
seckret_key: d4f'23p}793_+bg43'79'pd<./sabrg
